"""Per-concept quizzes. Generated by the LLM, graded here, scored into BKT."""

import uuid
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.ext.asyncio import AsyncSession

from database import get_session
from models import Concept, Quiz, User
from security import get_current_user
from services.learning import quiz as quiz_service
from services.llm.registry import get_client

router = APIRouter(prefix="/api/quiz", tags=["quiz"])


class GenerateIn(BaseModel):
    concept_id: uuid.UUID


class SubmitIn(BaseModel):
    quiz_id: uuid.UUID
    answers: dict[str, str]


@router.post("/generate")
async def generate(
    body: GenerateIn,
    session: AsyncSession = Depends(get_session),
    user: User = Depends(get_current_user),
):
    concept = await session.get(Concept, body.concept_id)
    if concept is None:
        raise HTTPException(404, "Unknown concept")

    client = await get_client()
    try:
        questions = await quiz_service.generate(client, concept.title, concept.summary)
    except quiz_service.QuizError as exc:
        raise HTTPException(502, str(exc)) from exc

    row = Quiz(
        user_id=user.id,
        concept_id=concept.id,
        questions={"items": questions},
    )
    session.add(row)
    await session.commit()

    return {
        "quizId": str(row.id),
        "conceptTitle": concept.title,
        "questions": quiz_service.for_client(questions),
    }


@router.post("/submit")
async def submit(
    body: SubmitIn,
    session: AsyncSession = Depends(get_session),
    user: User = Depends(get_current_user),
):
    row = await session.get(Quiz, body.quiz_id)
    if row is None or row.user_id != user.id:
        raise HTTPException(404, "No such quiz for this learner")

    outcome = await quiz_service.grade(session, row, body.answers)
    row.score = outcome["score"]
    row.submitted_at = datetime.now(timezone.utc)
    await session.commit()
    return outcome
