"""initial schema

Revision ID: 10b185bf19ce
Revises: 
Create Date: 2026-09-20 21:54:48.104065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import database


# revision identifiers, used by Alembic.
revision: str = '10b185bf19ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', database.GUID(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('accent', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('tenants',
    sa.Column('id', database.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concepts',
    sa.Column('id', database.GUID(length=36), nullable=False),
    sa.Column('subject_id', database.GUID(length=36), nullable=False),
    sa.Column('slug', sa.String(length=96), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('attributes', database.JSONDict(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'slug', name='uq_concept_subject_slug')
    )
    op.create_index(op.f('ix_concepts_subject_id'), 'concepts', ['subject_id'], unique=False)
    op.create_table('users',
    sa.Column('id', database.GUID(length=36), nullable=False),
    sa.Column('tenant_id', database.GUID(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('learner', 'guardian', 'educator', name='role'), nullable=False),
    sa.Column('education_level', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('chat_turns',
    sa.Column('id', database.GUID(length=36), nullable=False),
    sa.Column('user_id', database.GUID(length=36), nullable=False),
    sa.Column('concept_id', database.GUID(length=36), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('usage', database.JSONDict(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_turns_user_id'), 'chat_turns', ['user_id'], unique=False)
    op.create_table('concept_edges',
    sa.Column('id', database.GUID(length=36), nullable=False),
    sa.Column('source_id', database.GUID(length=36), nullable=False),
    sa.Column('target_id', database.GUID(length=36), nullable=False),
    sa.Column('relation', sa.Enum('prerequisite', 'related', 'confused_with', name='edgetype'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'target_id', 'relation', name='uq_concept_edge')
    )
    op.create_table('guardian_links',
    sa.Column('id', database.GUID(length=36), nullable=False),
    sa.Column('guardian_id', database.GUID(length=36), nullable=False),
    sa.Column('learner_id', database.GUID(length=36), nullable=False),
    sa.Column('invite_code', sa.String(length=12), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guardian_id', 'learner_id', name='uq_guardian_learner')
    )
    op.create_table('mastery',
    sa.Column('id', database.GUID(length=36), nullable=False),
    sa.Column('user_id', database.GUID(length=36), nullable=False),
    sa.Column('concept_id', database.GUID(length=36), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('observations', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'concept_id', name='uq_mastery_user_concept')
    )
    op.create_index(op.f('ix_mastery_concept_id'), 'mastery', ['concept_id'], unique=False)
    op.create_index(op.f('ix_mastery_user_id'), 'mastery', ['user_id'], unique=False)
    op.create_table('review_cards',
    sa.Column('id', database.GUID(length=36), nullable=False),
    sa.Column('user_id', database.GUID(length=36), nullable=False),
    sa.Column('concept_id', database.GUID(length=36), nullable=False),
    sa.Column('front', sa.Text(), nullable=False),
    sa.Column('back', sa.Text(), nullable=False),
    sa.Column('interval_days', sa.Float(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'concept_id', name='uq_card_user_concept')
    )
    op.create_table('sessions',
    sa.Column('id', database.GUID(length=36), nullable=False),
    sa.Column('user_id', database.GUID(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('review_cards')
    op.drop_index(op.f('ix_mastery_user_id'), table_name='mastery')
    op.drop_index(op.f('ix_mastery_concept_id'), table_name='mastery')
    op.drop_table('mastery')
    op.drop_table('guardian_links')
    op.drop_table('concept_edges')
    op.drop_index(op.f('ix_chat_turns_user_id'), table_name='chat_turns')
    op.drop_table('chat_turns')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_concepts_subject_id'), table_name='concepts')
    op.drop_table('concepts')
    op.drop_table('tenants')
    op.drop_table('subjects')
    # ### end Alembic commands ###
