"""add quizzes table

Revision ID: c1d005e18aed
Revises: 10b185bf19ce
Create Date: 2026-09-21 15:11:31.949324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# GUID and JSONDict (the app's dialect-portable column types) live here —
# autogenerate references them unqualified, so this import always precedes it.
import database


# revision identifiers, used by Alembic.
revision: str = 'c1d005e18aed'
down_revision: Union[str, Sequence[str], None] = '10b185bf19ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('id', database.GUID(length=36), nullable=False),
    sa.Column('user_id', database.GUID(length=36), nullable=False),
    sa.Column('concept_id', database.GUID(length=36), nullable=False),
    sa.Column('questions', database.JSONDict(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_concept_id'), 'quizzes', ['concept_id'], unique=False)
    op.create_index(op.f('ix_quizzes_user_id'), 'quizzes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quizzes_user_id'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_concept_id'), table_name='quizzes')
    op.drop_table('quizzes')
    # ### end Alembic commands ###
